### ISSUE TITLE
lakshmi.assets.NotFoundError: Cannot retrieve ticker ("VTI") from Yahoo Finance

### ISSUE THREAD

**Issue by mhenke** [sarvjeets/lakshmi#59]
Hi,

I haven't used lak for awhile.  I tried today and received this error:  lakshmi.assets.NotFoundError: Cannot retrieve ticker ("VTI") from Yahoo Finance.  I used the already setup portfolio for testing.

Below is the command I ran and the output.

mhenke@mhenke-Inspiron-15-3567:~$ lak --debug -r list assets total aa al performance
Traceback (most recent call last):
  File "/home/mhenke/.local/bin/lak", line 8, in <module>
    sys.exit(lak())
  File "/home/mhenke/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mhenke/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mhenke/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mhenke/.local/lib/python3.8/site-packages/click/core.py", line 1690, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/mhenke/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mhenke/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mhenke/.local/lib/python3.8/site-packages/lakshmi/lak.py", line 328, in assets
    output = portfolio.assets(
  File "/home/mhenke/.local/lib/python3.8/site-packages/lakshmi/lakshmi.py", line 712, in assets
    + [asset.name(), asset.adjusted_value()])
  File "/home/mhenke/.local/lib/python3.8/site-packages/lakshmi/assets.py", line 176, in adjusted_value
    return max(0, self.value() + self.get_what_if())
  File "/home/mhenke/.local/lib/python3.8/site-packages/lakshmi/assets.py", line 428, in value
    return self.shares() * self.price()
  File "/home/mhenke/.local/lib/python3.8/site-packages/lakshmi/cache.py", line 211, in new_func
    value = _call_func(class_obj, func)
  File "/home/mhenke/.local/lib/python3.8/site-packages/lakshmi/cache.py", line 178, in _call_func
    return func(class_obj)
  File "/home/mhenke/.local/lib/python3.8/site-packages/lakshmi/assets.py", line 539, in price
    raise NotFoundError(
lakshmi.assets.NotFoundError: Cannot retrieve ticker ("VTI") from Yahoo Finance

**Comment by mhenke** [comment]
ok, i ran **pip uninstall lakshmi** then **python -m pip install lakshmi** and the issue seems resolved
